version: '3.9'

services:

  mysql:
    image: mariadb:10.7.4-focal
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wp_net

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    container_name: wordpress
    ports:
      - ${WORDPRESS_PORT}:80
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wp_data:/var/www/html:rw
    networks:
      - wp_net

  wp-cli:
    depends_on:
      - mysql
      - wordpress
    image: wordpress:cli
    container_name: wp-cli
    env_file: .env
    user: xfs
    environment:
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wp_data:/var/www/html:rw
      - ./wp_setup.sh:/usr/local/bin/wp_setup:ro
    networks:
      - wp_net

volumes:
  db_data:
  wp_data:

networks:
  wp_net:
    driver: bridge
